# Config File

adapters:
  ILLUMINACLIP:NexteraPE-PE.fa:2:30:10:8:true

bt2_genome:
  /home/groups/Agarwal_A_Data/Luiza/chip-seq/genomes/ucsc/hg38/indexes/bowtie/hg38

gtf:
  /home/groups/Agarwal_A_Data/Luiza/chip-seq/genomes/ucsc/hg38/annotation/hg38.ncbiRefSeq.gtf

mt_chr:
  chrM

effective_genome_size:
  2913022398

macs2_genome:
  hs

contrasts:
  - Iso_vs_Ctrl
  - Rux_vs_Ctrl
  - Rap_vs_Ctrl

analysis_method:
  DBA_EDGER

min_overlap:
  2

fdr_cutoff:
  0.05

data_source:
  hg38

organism:
  Homo_sapiens
